name: Docs To Github Pages
on:
  push:
    branches:
      - "main"
      - "develop"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: installNode
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Build
        run: npm install && npm run build-storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          FOLDER: storybook-static
          CLEAN: true
